[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = "default-src 'self'; connect-src 'self' https://*.supabase.co https://*.supabase.insecure wss://*.supabase.co wss://*.supabase.insecure; img-src 'self' data: https:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com; frame-src https://*.supabase.co;"
